# Generated by Django 3.2.9 on 2023-05-25 09:00

import django.db.models.deletion
from django.db import migrations, models

import authentik.sources.ldap.models


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_crypto", "0003_certificatekeypair_managed"),
        ("authentik_sources_ldap", "0001_squashed_0012_auto_20210812_1703"),
        ("authentik_sources_ldap", "0002_auto_20211203_0900"),
    ]

    operations = [
        migrations.AddField(
            model_name="ldapsource",
            name="client_certificate",
            field=models.ForeignKey(
                default=None,
                help_text=(
                    "Client certificate to authenticate against the LDAP Server's Certificate."
                ),
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="authentik_crypto.certificatekeypair",
            ),
        ),
        migrations.AlterField(
            model_name="ldapsource",
            name="server_uri",
            field=models.TextField(
                validators=[
                    authentik.sources.ldap.models.MultiURLValidator(schemes=["ldap", "ldaps"])
                ],
                verbose_name="Server URI",
            ),
        ),
    ]
