# Generated by Django 4.1.7 on 2023-06-04 00:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentik_sources_ldap", "0003_auto_20230531_2200"),
    ]

    operations = [
        migrations.AddField(
            model_name="ldapsource",
            name="sni",
            field=models.BooleanField(
                default=False, verbose_name="Use Server URI for SNI verification"
            ),
        ),
    ]
